### ISSUE TITLE
Nice paper. Attention mechanism?

### ISSUE THREAD

**Issue by bw4sz** [shenzhouchn/Temporal-3D-RetinaNet-for-fish-detection#1]
Just finished reading your [paper](http://www.dicta2020.org/wp-content/uploads/2020/09/43_CameraReady.pdf), great work. I've been using 2D retinanets for tree detection
[deepforest](https://deepforest.readthedocs.io/). I've been planning temporal tree detection for the winter, I will probably use some ideas from this repo once the code is made available. 

The biology community has also been collecting benchmark datasets at http://lila.science/. Please consider depositing your data when ready, or place it on zenodo so it can be archived. @agentmorris maintains the archive. 

One question:

Is there any attention mechanism possible in this architecture, for example see @s et al. 2020 (https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Beery_Context_R-CNN_Long_CVPR_2020_supplemental.pdf). How does the model learn which features to use from previous images, or does it just concat all features equally? Figure 3 says 'combine' which I assume just means concatenate into one vector.

Thanks for making your work open source and continue building expertise in this area.

**Comment by shenzhouchn** [comment]
Thank you for your interest. The model concats all features equally and doesn't use attention mechanisms.
